### ISSUE TITLE
CSS not loading if dashicons is deregistered?

### ISSUE THREAD

**Issue by armandn** [yo35/rpb-chessboard#204] opened 2021-05-29 09:31 UTC
Here's something very strange: If I use `wp_deregister_style('dashicons');` in functions.php, then RPB doesn't load any CSS.

**Comment by yo35** [comment] 2021-05-29 13:00
Hi,
This may be related to your theme (by the way: which one is it?).

Also, have you tried to disable lazy-loading of CSS/JavaScript files? (in the admin, menu 'Chess' > 'Settings' > 'Compatibility settings') Do you observe the same behavior while disabling this feature?

**Comment by armandn** [comment] 2021-05-29 13:56
It's a theme I made based on an old Theme Hybrid framework. It's very well-behaved, I've had zero issues in 7 years.

I'll have a look at compatibility settings and interactions with other plugins. I'm building a testing environment for this.

**Comment by yo35** [comment] 2021-05-29 14:48
When lazy-loading is enabled, the CSS and JavaScript files needed by the plugin are enqueued only if a `[fen]...[/fen]` or `[pgn]...[/pgn]` shortcode is encountered in the rendered WordPress page/post. But the problem is that, with this strategy, the header of the HTML page has already been rendered when encountering a a `[fen]...[/fen]` or `[pgn]...[/pgn]` shortcode, thus the CSS and JavaScript files are enqueued as part of the footer section of the page.

And of course, if there is no footer section, then lazy-loading does not work properly.

More details in #135

**Comment by yo35** [comment] 2022-06-13 08:37
I've re-investigated this issue, and in fact the origin of the problem is quite clear: the CSS sheet loaded by RPB Chessboard declares a dependency on `wp-jquery-ui-dialog` (which is part of WP core):

```
wp_register_style( 'rpbchessboard-npm', ..., array( 'wp-jquery-ui-dialog' ), ... );
```

... and in turn `wp-jquery-ui-dialog` declares a dependency on `dashicons` (see in /wp-includes/script-loader.php line 1544). Since `dashicons` is unregistered, neither `wp-jquery-ui-dialog` nor `rpbchessboard-npm` can be loaded.

So my guess is that if you de-register the CSS `dashicons`, you must ensure that `wp-jquery-ui-dialog` can still be loaded properly.

**Comment by yo35** [comment] 2023-03-05 10:15
Closing as the malfunction does not originate from RPB Chessboard.

**Closed by yo35** 2023-03-05 10:15 UTC
