### ISSUE TITLE
Unrecognized Space in PGN

### ISSUE THREAD

**Issue by ErickHoxter** [yo35/rpb-chessboard#74] opened 2016-10-19 22:09 UTC
Hello I'm receiving an error in my pgn. It says after move 8 and before move 9 there is an unrecognized character or string of characters. I can't seem to figure out what the issue is. Any ideas?

[pgn]

[Event "WUCI Chess Festival "]
[Site "Wilmington YMCA"]
[Date "Oct 15, 2016"]
[Round "3"]
[White "Josep Mucerino Jr 2160"]
[Black "Erick Hoxter 1449"]
[Result "1-0"]
1. d4 Nf6 2. Nf3 d5 3. e3 Bg4 4. c4 e6

{[pgndiagram]a colle system of sorts. The expert is looking for a solid, non theoretical, flexible system that will allow him to work a small advantage.}

5.Qb3

{uh oh... Maybe that's not what he's looking for. He continues to blitz out moves without a second thought. Only this time he's getting more aggressive.

The entire game I've been on my heels, playing at his pace and noting his facial expressions. I was mentally unprepared and it showed in the lack of concentration and calculation from black.}

5...b6

{you see...}

(11...Qc8{Clearly this was a much better option. It doesn't weaken the light squares and solidly defends everything. So why didn't black play that move? Another expert chalks it up to inexperience. Surely black has encountered a situation where his g or b pawn is targeted by the opposing queen with his own rook still stuck in the corner. It seems as though the star-stricken nerves are getting the best of him this game. He's more focused on looking like he knows what he's doing by blitzing out moves in a standard game.})
1. Ne5 Nbd7 7. Nc6 Qc8 {[pgndiagram] taking advantage of black's light square weakness.}
2. cxd5 Nxd5 9. Qa4 Qb7 10. Ne5 (10. Ba6 {wins immediately.} 10... b5 {A forced effort. While a valiant attempt to hold, black is still lost after} 11. Bxb7 bxa4 12. Bxa8 {and black is busted.}) 10... Nf6 11. Bb5 Rd8 12. Bc6 b5 13. Bxb7 bxa4 14. Nc6 Rb8
3. Nxb8 Nxb8 16. Bf3 Bf5 17. Nc3 Bb4 18. Bd2 O-O 19. Nxa4 Nc6 20. Bxc6
   1-0 [/pgn]

**Comment by yo35** [comment] 2016-10-20 19:31
Hi,
Unfortunately I cannot reproduce your problem, it works fine for me... Did you try to remove the end of the game to see which move causes the issue?

**Comment by yo35** [comment] 2018-01-21 12:45
No answer since October 2016 => I close the issue.

**Closed by yo35** 2018-01-21 12:45 UTC
