### ISSUE TITLE
"Initial position"

### ISSUE THREAD

**Issue by snusfornuftig** [yo35/rpb-chessboard#194] opened 2021-01-30 04:13 UTC
Hey! 
On a new page I'm setting up, I'm getting a "Initial Position" message instead of the game. [fen]-kode works on the page, but not [pgn]. I've tested and get the correct error messages, and when changing into a pgn that works the error message "Initial Position" shows up. 

Have tried with all different settings under compability settings, but no luck. 
Note. FEN only works when "Lazy-loading for CSS/JavaScript files" is enabled.

Any tips?

**Comment by yo35** [comment] 2021-01-30 09:58
Hi,
It seems to a problem with your theme. Which one is it?
Also, do you have the address of a webpage on which the problem appears?

**Comment by snusfornuftig** [comment] 2021-01-30 12:02
Hi! Thanks for the quick reply!
I think it's a problem with the plugin Memberpress, as it happens only on the courses there, not on regular blogposts.
An example page is here: https://sjakktrening.no/kursplan/hvordan-spille-mot-skandinavisk/lessons/uvanlige-fortsettelser/

**Comment by yo35** [comment] 2021-01-31 09:59
The problem is that, for some reason, the CSS required to display the `[pgn][/pgn]` widget is missing. More specifically, the required CSS files are:
- https://sjakktrening.no/wp-content/plugins/rpb-chessboard/css/rpbchess-ui-chessboard.min.css
- https://sjakktrening.no/wp-content/plugins/rpb-chessboard/css/rpbchess-ui-chessgame.min.css
- https://sjakktrening.no/wp-content/plugins/rpb-chessboard/css/frontend.min.css
- https://sjakktrening.no/wp-content/plugins/rpb-chessboard/third-party-libs/jquery/jquery-ui.smoothness.min.css
- https://sjakktrening.no/wp-includes/css/jquery-ui-dialog.min.css

I don't understand why those CSS are missing, especially since there is no problem with the chessboard widget inserted with `[fen][/fen]` (in this case, only https://sjakktrening.no/wp-content/plugins/rpb-chessboard/css/rpbchess-ui-chessboard.min.css is required, and the file is there...).

Maybe memberpress "blocks" those files ? I don't know, and I cannot investigate the problem further since Memberpress is not a free plugin.

**Comment by snusfornuftig** [comment] 2021-02-01 09:31
Thank you so much for checking that out! I was a bit on deep water here, but now I'm closer and can contact the Memberpress developer for some help. Thanks! Love your addon!

**Comment by yo35** [comment] 2021-05-30 15:57
@snusfornuftig Did you get any feedback from the Memberpress developer team? Is is possible to close this issue?

**Comment by snusfornuftig** [comment] 2021-07-07 18:58
Hey, sorry for the late reply. Yes, they helped and you can close this. Really sorry for the late reply!

**Closed** 2021-07-07 19:20 UTC
