### ISSUE TITLE
Arrows don't appear properly when the plugin is first displayed in a Details -> Summary HTML element.

### ISSUE THREAD

**Issue by leonfresh** [yo35/rpb-chessboard#185] opened 2020-10-20 09:05 UTC
Hello I'm using Details and Summary HTML elements, and the arrow-head doesn't appear if the first RPB chessboard is within one. It works fine if the first RPB chessboard is not within a details element. 

https://chesstuts.com/amazing-tactics-positional-plans-that-happened-in-my-games/

**Comment by yo35** [comment] 2020-11-16 10:32
Hi,
Again, sorry for the late reply. Is there a page in your website in which the problem appears? It's easier to understand what is wrong on an example.

**Comment by leonfresh** [comment] 2020-11-16 11:50
Is it possible for you to try yourself? Here's the HTML for detail and
summary, place this in a new wordpress article and for me there will be no
arrow-heads graphics being rendered (assuming this is the only pgn in the
article).

<details>
    <summary>Details</summary>
    [pgn navigation_Board=scrollLeft]
         add a game pgn here
    [/pgn]
</details>

**Comment by yo35** [comment] 2020-11-16 16:30
I didn't know that `<details>` feature in HTML, I thought it was something brought by a custom WordPress plugin or something... Anyway.

I cannot reproduce the problem on my side: I've created a new article, put a diagram within a `<details>` HTML tag, ensured that there is no other RPB chessboard content in the page, but when I open `<details>` block, the the arrow looks OK:
![diagram_in_details](https://user-images.githubusercontent.com/5740068/99279453-8a5faf80-2830-11eb-9251-532c5e973197.png)

I've tried both with a `[fen]` diagram or with an inline diagram within a `[pgn]` game, same behavior.

This may be a browser-specific issue. I've tried with Firefox 82 and Chrome 86, no problem. What is your browser?

This may also be related to your theme, and in this case, it would be easier to figure out what is wrong if you could provide me a with an example of a page showing the problem.

**Comment by leonfresh** [comment] 2020-11-18 09:58
Oh sorry, I meant where there were multiple ones. Here's an example (temp
url link)

https://chesstuts.com/test/

**Comment by leonfresh** [comment] 2020-11-18 10:03
The first one is fine but the 2nd isn't.

**Comment by yo35** [comment] 2020-11-18 14:21
OK, I see. Thanks for the demo, I'm now able to reproduce it on my side.

**Comment by yo35** [comment] 2020-11-18 16:12
Fixed in version 5.8.1

**Closed by yo35** 2020-11-18 16:12 UTC
Labels: bug
